### PR TITLE
Hash keys ending in ? or ! should be converted

### PR DESCRIPTION
**Pull request by jaredmoody**

### CODE REVIEW

**Comment by iltempo** [comment]
I did not know that exclamation marks and question marks are allowed in the middle of a method name. But they are.

**Comment by iltempo** [comment]
But as hash keys these signs are only allowed at the end of the key. What do you think about changing the regex like this?

`([^\:])\:([a-zA-Z_0-9]+[\?\!]?)(\s*)=\>(\s*)`

**Comment by jaredmoody** [comment]
Looks good to me. You want to put that in or should I update the PR?

**Comment by iltempo** [comment]
If you would it to the pull request I would be fine.

**Comment by jaredmoody** [comment]
Updated.

**Comment by iltempo** [comment]
Thanks a lot!

**Pull request merged**
