### PR TITLE
Add a command for converting hashes

### PR DESCRIPTION
**Pull request by jaredmoody**
Useful for me, maybe for others too, what do you think?

### CODE REVIEW

**Comment by jaredmoody** [comment]
Added ! and ? to the regex so hashes with those keys also get converted

**Comment by ronny** [comment]
This will be really useful for me since I tend to not bother memorizing keyboard shortcuts for things that I don't use often. I don't see any harm in merging this in since this won't affect current usage (although the commit about fixing the regex could be in a separate pull request).

**Comment by iltempo** [comment]
Thank you for this pull request. Would you mind splitting it up into two?
Please add another one for the ? and !.

**Comment by jaredmoody** [comment]
Will do.

**Pull request closed without merging**
